// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;
using TASKSERVICE.Infrastructure.Context;

#nullable disable

namespace TASKSERVICE.Infrastructure.Migrations
{
    [DbContext(typeof(TaskDbContext))]
    [Migration("20250517085008_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TASKSERVICE.Core.Entities.TaskItems", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("RAW(16)")
                        .HasColumnName("ID");

                    b.Property<Guid>("AssignedToUserId")
                        .HasColumnType("RAW(16)")
                        .HasColumnName("ASSIGNED_TO_USER_ID");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("RAW(16)")
                        .HasColumnName("CREATED_BY_USER_ID");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("DESCRIPTION");

                    b.Property<DateTime>("DueDate")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DUE_DATE");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("STATUS");

                    b.Property<Guid>("TeamId")
                        .HasColumnType("RAW(16)")
                        .HasColumnName("TEAM_ID");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("NVARCHAR2(200)")
                        .HasColumnName("TITLE");

                    b.HasKey("Id");

                    b.ToTable("PRACTICE_TASKS", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
