// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;
using USERSERVICE.InfrastructureDB.Context;

#nullable disable

namespace USERSERVICE.InfrastructureDB.Migrations
{
    [DbContext(typeof(UserDbContext))]
    partial class UserDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("USERSERVICE.Core.Entities.AppUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("RAW(16)")
                        .HasColumnName("ID");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("EMAIL");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("FULLNAME");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("NVARCHAR2(255)")
                        .HasColumnName("PASSWORD_HASH");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("NVARCHAR2(20)")
                        .HasColumnName("ROLE");

                    b.HasKey("Id");

                    b.ToTable("SELISE_USERS", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("e492bcad-e565-44e7-a48f-a0759783da98"),
                            Email = "admin@demo.com",
                            FullName = "Admin User",
                            PasswordHash = "$2a$11$OGnuVANAu5j7DAaJYqMNYegDrPQT4HkH0z5JrOhxdCbGTV9jL4kG6",
                            Role = "Admin"
                        },
                        new
                        {
                            Id = new Guid("38603a1b-8b8d-4305-83bf-c0b1bd83bed6"),
                            Email = "manager@demo.com",
                            FullName = "Manager User",
                            PasswordHash = "$2a$11$uWfSc5TU0z2U5BYb5H.DUOACrijkRabHxV1IjxNu6LEquIB7C5/DW",
                            Role = "Manager"
                        },
                        new
                        {
                            Id = new Guid("780516b4-851e-457e-9786-542f69de070b"),
                            Email = "employee@demo.com",
                            FullName = "Employee User",
                            PasswordHash = "$2a$11$3aebbEQpGuBcj0Q08.RNn.avs/d0ILcU2r6n/BXaneaAkKPMoR0ku",
                            Role = "Employee"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
